using System;
using Autodesk.AutoCAD.DatabaseServices;
using ThMEPStructure.Reinforcement.Model;

namespace ThMEPStructure.Reinforcement.Draw
{
    public static class ThEdgeComponentExtension
    {
        public static DBObjectCollection Draw(this ThRectangleEdgeComponent rectEdgeComponent)
        {
            throw new NotImplementedException();
        }
        public static DBObjectCollection Draw(this ThLTypeEdgeComponent lTypeEdgeComponent)
        {
            throw new NotImplementedException();
        }
        public static DBObjectCollection Draw(this ThTTypeEdgeComponent lTypeEdgeComponent)
        {
            throw new NotImplementedException();
        }
    }
}
