using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Autodesk.AutoCAD.Geometry;
using Autodesk.AutoCAD.DatabaseServices;

using AcHelper;
using Linq2Acad;
using GeometryExtensions;
using NFox.Cad;

using ThCADCore.NTS;
using ThCADExtension;
using ThMEPEngineCore;
using ThMEPEngineCore.Algorithm;
using ThMEPEngineCore.Command;
using ThMEPEngineCore.Model;
using ThMEPEngineCore.IO;
using ThMEPEngineCore.IO.GeoJSON;
using ThMEPEngineCore.Config;

namespace ThMEPLighting.IlluminationLighting.Model
{
    //class ThLayoutResult
    //{
    //    //public List<ThLayoutPts> layoutPts { get; set; } = new List<ThLayoutPts>();
    //    //public List<Polyline> blind { get; set; } = new List<Polyline>();
        
    //}
}
