<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{9F81D0C6-08FE-451E-9379-5882F9270E55}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>ThMEPElectrical</RootNamespace>
    <AssemblyName>ThMEPElectrical</AssemblyName>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <Deterministic>true</Deterministic>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <Import Project="..\TIANHUA.CSharp.General.targets" />
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Assistant\GeometryTrans.cs" />
    <Compile Include="Block\BlockInsertDBExtension.cs" />
    <Compile Include="Business\BlockInsertor.cs" />
    <Compile Include="Business\CalculateDetection.cs" />
    <Compile Include="Business\CalculateLayout.cs" />
    <Compile Include="Business\EntityPicker.cs" />
    <Compile Include="Business\PlacePointCalculator.cs" />
    <Compile Include="Business\MainBeam\MultiSegmentPlace.cs" />
    <Compile Include="Business\MainBeam\OneColMultiSegmentsPlace.cs" />
    <Compile Include="Business\MainBeam\OneColRectPlace.cs" />
    <Compile Include="Business\PolygonProfilePlace.cs" />
    <Compile Include="Business\MainBeam\RectProfilePlace.cs" />
    <Compile Include="CAD\DBExtract.cs" />
    <Compile Include="Core\PackageManager.cs" />
    <Compile Include="Assistant\DrawUtils.cs" />
    <Compile Include="Geometry\ABBRectangle.cs" />
    <Compile Include="Geometry\CoordinateTransform.cs" />
    <Compile Include="Geometry\GeomUtils.cs" />
    <Compile Include="Geometry\MinRectangle.cs" />
    <Compile Include="Layout\ILayout.cs" />
    <Compile Include="Layout\MainBeamLayout.cs" />
    <Compile Include="Layout\MainBeamPolygonLayout.cs" />
    <Compile Include="Layout\MainBeamRectangleLayout.cs" />
    <Compile Include="Layout\MainSecondBeamLayout.cs" />
    <Compile Include="Layout\MainSecondBeamPolygonLayout.cs" />
    <Compile Include="Layout\MainSecondBeamRectangleLayout.cs" />
    <Compile Include="Layout\SensorLayout.cs" />
    <Compile Include="Layout_Braodcast\ColumnService.cs" />
    <Compile Include="Layout_Braodcast\InsertBroadcastService.cs" />
    <Compile Include="Layout_Braodcast\LayoutService.cs" />
    <Compile Include="Layout_Braodcast\ParkingLinesService.cs" />
    <Compile Include="Model\BeamProfile.cs" />
    <Compile Include="Model\ColumnModel.cs" />
    <Compile Include="Model\DetectionRegion.cs" />
    <Compile Include="Model\LayoutMap.cs" />
    <Compile Include="Model\LayoutProfileData.cs" />
    <Compile Include="Model\PlaceInputProfileData.cs" />
    <Compile Include="Model\PlaceParameter.cs" />
    <Compile Include="Model\PlacePoint.cs" />
    <Compile Include="Model\PlacePointProArea.cs" />
    <Compile Include="Model\PlaceRect.cs" />
    <Compile Include="PostProcess\Adjustor\NonRegularPlacePointAdjustor.cs" />
    <Compile Include="PostProcess\Adjustor\PointAdjustor.cs" />
    <Compile Include="PostProcess\ConstraintInterface\IBeautifyConstraint.cs" />
    <Compile Include="PostProcess\ConstraintInterface\IDistanceConstraint.cs" />
    <Compile Include="PostProcess\PlacePointAdjustor.cs" />
    <Compile Include="PostProcess\Adjustor\RegularPlacePointAdjustor.cs" />
    <Compile Include="ThMEPCommon.cs" />
    <Compile Include="ThMEPElectricalApp.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DotNetARX\2010\DotNetARX.csproj">
      <Project>{5ddfcada-bea4-402c-b3e4-5c7f83c2f09e}</Project>
      <Name>DotNetARX</Name>
    </ProjectReference>
    <ProjectReference Include="..\ThCADCore\ThCADCore.csproj">
      <Project>{c6ac9e68-9059-4ddd-8fa7-58e2656d572e}</Project>
      <Name>ThCADCore</Name>
    </ProjectReference>
    <ProjectReference Include="..\ThMEPEngineCore\ThMEPEngineCore.csproj">
      <Project>{ad98390a-569d-4774-aa3e-d9f00bc84cd6}</Project>
      <Name>ThMEPEngineCore</Name>
    </ProjectReference>
    <ProjectReference Include="..\Utilities\ExtensionTools.csproj">
      <Project>{8a2e6fb5-12f2-4406-8109-d9ddc8452dfd}</Project>
      <Name>ExtensionTools</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Business\MainSecondBeam\" />
    <Folder Include="View\" />
  </ItemGroup>
  <Choose>
    <When Condition="$(DefineConstants.Contains('ACAD2012'))">
      <ItemGroup>
        <PackageReference Include="AutoCAD-2012.Net.Base" Version="1.0.0" />
        <PackageReference Include="AutoCAD-2012.Net.Interop.x64" Version="1.0.0" />
      </ItemGroup>
    </When>
    <When Condition="$(DefineConstants.Contains('ACAD2014'))">
      <ItemGroup>
        <PackageReference Include="AutoCAD-2014.Net.Base" Version="1.0.0" />
        <PackageReference Include="AutoCAD-2014.Net.Interop.x64" Version="1.0.0" />
      </ItemGroup>
    </When>
    <When Condition="$(DefineConstants.Contains('ACAD2016'))">
      <ItemGroup>
        <PackageReference Include="AutoCAD-2016.Net.Base" Version="1.0.0" />
        <PackageReference Include="AutoCAD-2016.Net.Interop.x86" Version="1.0.0" />
      </ItemGroup>
    </When>
    <When Condition="$(DefineConstants.Contains('ACAD2018'))">
      <ItemGroup>
        <PackageReference Include="AutoCAD.NET" Version="22.0.0" />
        <PackageReference Include="AutoCAD.NET.Core" Version="22.0.0" />
        <PackageReference Include="AutoCAD.NET.Model" Version="22.0.0" />
      </ItemGroup>
      <ItemGroup>
        <Reference Include="Autodesk.AutoCAD.Interop.dll">
          <HintPath>..\..\Externals\AutoCAD\2018\Autodesk.AutoCAD.Interop.dll</HintPath>
        </Reference>
        <Reference Include="Autodesk.AutoCAD.Interop.Common.dll">
          <HintPath>..\..\\Externals\AutoCAD\2018\Autodesk.AutoCAD.Interop.Common.dll</HintPath>
        </Reference>
      </ItemGroup>
    </When>
  </Choose>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>